/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ArrowLongIcon: typeof import('./src/components/ArrowLongIcon.vue')['default']
    Booking: typeof import('./src/components/Booking/Booking.vue')['default']
    BuyoutType: typeof import('./src/components/Booking/BuyoutType.vue')['default']
    Checkout: typeof import('./src/components/Booking/Checkout/Checkout.vue')['default']
    Counter: typeof import('./src/components/Booking/Guests/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Guests: typeof import('./src/components/Booking/Guests/Guests.vue')['default']
    GuestsCount: typeof import('./src/components/Booking/Guests/guestsCount.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    RoomInfo: typeof import('./src/components/Booking/RoomSelect/RoomInfo.vue')['default']
    RoomSelect: typeof import('./src/components/Booking/RoomSelect/RoomSelect.vue')['default']
  }
}
